# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\cc\Desktop\AI_system\lab\lab3\mysql文件\dialog1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog1(object):
    def setupUi(self, Dialog1):
        Dialog1.setObjectName("Dialog1")
        Dialog1.resize(515, 270)
        self.comboBox = QtWidgets.QComboBox(Dialog1)
        self.comboBox.setGeometry(QtCore.QRect(140, 90, 78, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(Dialog1)
        self.label.setGeometry(QtCore.QRect(50, 50, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog1)
        self.label_2.setGeometry(QtCore.QRect(70, 90, 63, 13))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog1)
        self.lineEdit.setGeometry(QtCore.QRect(140, 140, 71, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Dialog1)
        self.label_3.setGeometry(QtCore.QRect(80, 140, 63, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog1)
        self.label_4.setGeometry(QtCore.QRect(280, 50, 81, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog1)
        self.label_5.setGeometry(QtCore.QRect(300, 90, 63, 13))
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog1)
        self.lineEdit_2.setGeometry(QtCore.QRect(370, 90, 71, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(Dialog1)
        self.label_6.setGeometry(QtCore.QRect(300, 140, 63, 13))
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog1)
        self.lineEdit_3.setGeometry(QtCore.QRect(370, 140, 71, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog1)
        self.lineEdit_4.setGeometry(QtCore.QRect(370, 190, 71, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(Dialog1)
        self.label_7.setGeometry(QtCore.QRect(300, 190, 63, 13))
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(Dialog1)
        self.pushButton.setGeometry(QtCore.QRect(200, 220, 82, 25))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog1)
        QtCore.QMetaObject.connectSlotsByName(Dialog1)

    def retranslateUi(self, Dialog1):
        _translate = QtCore.QCoreApplication.translate
        Dialog1.setWindowTitle(_translate("Dialog1", "系统设置"))
        self.comboBox.setItemText(0, _translate("Dialog1", "COM1"))
        self.comboBox.setItemText(1, _translate("Dialog1", "COM2"))
        self.comboBox.setItemText(2, _translate("Dialog1", "COM3"))
        self.comboBox.setItemText(3, _translate("Dialog1", "/dev/cu.usbmodem14201\n"
""))
        self.label.setText(_translate("Dialog1", "通信设置"))
        self.label_2.setText(_translate("Dialog1", "通信端口："))
        self.label_3.setText(_translate("Dialog1", "数据位："))
        self.label_4.setText(_translate("Dialog1", "红绿灯设置"))
        self.label_5.setText(_translate("Dialog1", "周期时长："))
        self.label_6.setText(_translate("Dialog1", "黄灯时长："))
        self.label_7.setText(_translate("Dialog1", "最短绿灯："))
        self.pushButton.setText(_translate("Dialog1", "设置"))
