# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\cc\Desktop\AI_system\lab\lab4\code\UI_design\dialogBaiduData.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_baiduData(object):
    def setupUi(self, Dialog_baiduData):
        Dialog_baiduData.setObjectName("Dialog_baiduData")
        Dialog_baiduData.resize(618, 394)
        self.label_4 = QtWidgets.QLabel(Dialog_baiduData)
        self.label_4.setGeometry(QtCore.QRect(230, 40, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(Dialog_baiduData)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 111, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog_baiduData)
        self.lineEdit.setGeometry(QtCore.QRect(170, 40, 51, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog_baiduData)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 40, 51, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(Dialog_baiduData)
        self.label_3.setGeometry(QtCore.QRect(140, 40, 31, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Dialog_baiduData)
        self.pushButton.setGeometry(QtCore.QRect(330, 40, 82, 25))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget_2 = QtWidgets.QTableWidget(Dialog_baiduData)
        self.tableWidget_2.setGeometry(QtCore.QRect(70, 70, 471, 261))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)

        self.retranslateUi(Dialog_baiduData)
        QtCore.QMetaObject.connectSlotsByName(Dialog_baiduData)

    def retranslateUi(self, Dialog_baiduData):
        _translate = QtCore.QCoreApplication.translate
        Dialog_baiduData.setWindowTitle(_translate("Dialog_baiduData", "百度路况数据表"))
        self.label_4.setText(_translate("Dialog_baiduData", "--"))
        self.label_2.setText(_translate("Dialog_baiduData", "数据查询"))
        self.label_3.setText(_translate("Dialog_baiduData", "ID："))
        self.pushButton.setText(_translate("Dialog_baiduData", "查询"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_baiduData", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_baiduData", "采集时间"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_baiduData", "东西路况"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Dialog_baiduData", "南北路况"))
