# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\cc\Desktop\AI_system\lab\lab4\code\UI_design\dialog14.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog14(object):
    def setupUi(self, Dialog14):
        Dialog14.setObjectName("Dialog14")
        Dialog14.resize(645, 487)
        self.tableWidget = QtWidgets.QTableWidget(Dialog14)
        self.tableWidget.setGeometry(QtCore.QRect(30, 60, 571, 401))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.label = QtWidgets.QLabel(Dialog14)
        self.label.setGeometry(QtCore.QRect(50, 30, 63, 13))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog14)
        self.pushButton.setGeometry(QtCore.QRect(150, 20, 82, 25))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Dialog14)
        self.lineEdit.setGeometry(QtCore.QRect(380, 30, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog14)
        self.label_2.setGeometry(QtCore.QRect(290, 30, 81, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog14)
        QtCore.QMetaObject.connectSlotsByName(Dialog14)

    def retranslateUi(self, Dialog14):
        _translate = QtCore.QCoreApplication.translate
        Dialog14.setWindowTitle(_translate("Dialog14", "解释器表"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog14", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog14", "传感器数据ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog14", "解释"))
        self.label.setText(_translate("Dialog14", "解释器表"))
        self.pushButton.setText(_translate("Dialog14", "查询"))
        self.label_2.setText(_translate("Dialog14", "传感器数据ID"))
